- config_name: "B128_flex_all"
  min_seq_len: 10
  max_seq_len: 30
  val_ratio: 0.2
  batch_size: 128
  hidden_size: 128
  epoch: 3000
  learning_rate: 1e-3
  weight_decay: 1e-3
  teacher_forcing: 0.2
  layers: 1

- config_name: "B128_flex_all_fat"
  min_seq_len: 10
  max_seq_len: 30
  val_ratio: 0.2
  batch_size: 128
  hidden_size: 1024
  epoch: 3000
  learning_rate: 1e-3
  weight_decay: 1e-3
  teacher_forcing: 0.2
  layers: 1

- config_name: "B256_flex_all"
  min_seq_len: 10
  max_seq_len: 30
  val_ratio: 0.2
  batch_size: 256
  hidden_size: 128
  epoch: 3000
  learning_rate: 1e-3
  weight_decay: 1e-3
  teacher_forcing: 0.2
  layers: 1

- config_name: "B64_flex_all"
  min_seq_len: 10
  max_seq_len: 30
  val_ratio: 0.2
  batch_size: 64
  hidden_size: 128
  epoch: 3000
  learning_rate: 1e-3
  weight_decay: 1e-3
  teacher_forcing: 0.2
  layers: 1

- config_name: "B32_flex_all"
  min_seq_len: 10
  max_seq_len: 30
  val_ratio: 0.2
  batch_size: 32
  hidden_size: 128
  epoch: 3000
  learning_rate: 1e-3
  weight_decay: 1e-3
  teacher_forcing: 0.2
  layers: 1